name: Build Android GSI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jdk bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/cmdline-tools/bin:\$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        source $GITHUB_ENV
        yes | $ANDROID_HOME/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30"

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=$PATH:$HOME/bin' >> $GITHUB_ENV

    - name: Source Environment
      run: source $GITHUB_ENV

    - name: Verify Repo Installation
      run: |
        source $GITHUB_ENV
        echo "Repo version:"
        ~/bin/repo --version

    - name: Initialize Repo
      run: |
        source $GITHUB_ENV
        ~/bin/repo init -u https://android.googlesource.com/platform/manifest -b android-15-qpr2-beta-1-gpl

    - name: Sync Repo
      run: |
        source $GITHUB_ENV
        ~/bin/repo sync -cq

    - name: Set Up Build Environment
      run: |
        source $GITHUB_ENV
        source build/envsetup.sh

    - name: Lunch Configuration
      run: |
        source $GITHUB_ENV
        lunch gsi_arm64-userdebug

    - name: Build GSI
      run: |
        source $GITHUB_ENV
        make -j4

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gsi-build
        path: out/target/product/gsi_arm64/
